# Generated by Django 4.1 on 2023-09-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorWeb', '0003_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannedwebsite',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='long_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='websitetraffic',
            name='url',
            field=models.URLField(),
        ),
    ]
