# Generated by Django 4.1 on 2023-09-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorWeb', '0007_vulnerability'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('is_vulnerable', models.BooleanField(default=False)),
                ('scan_result', models.TextField(blank=True)),
            ],
        ),
    ]
