# Generated by Django 4.1 on 2023-09-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorWeb', '0008_scannedurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitetraffic',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
