# Generated by Django 4.1 on 2023-09-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorWeb', '0009_alter_websitetraffic_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
