# Generated by Django 4.1 on 2023-10-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorWeb', '0011_csfscannerresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='SQLInjectionScannerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('is_vulnerable', models.BooleanField()),
            ],
        ),
    ]
