# Generated by Django 4.0 on 2023-10-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorWeb', '0014_scanresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='NmapScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField()),
                ('scan_result', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ScanResult',
        ),
    ]
