# Generated by Django 4.0 on 2023-10-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorWeb', '0015_nmapscanresult_delete_scanresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='OWASPSecurityScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField()),
                ('scan_result', models.TextField()),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SQLInjectionScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('is_vulnerable', models.BooleanField(default=False)),
                ('scan_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
