# Generated by Django 4.0 on 2023-10-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorWeb', '0016_owaspsecurityscan_sqlinjectionscanresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('ip_address', models.GenericIPAddressField()),
                ('response_time', models.FloatField()),
            ],
        ),
    ]
