# Generated by Django 4.0 on 2023-10-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorWeb', '0017_ping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ping',
        ),
        migrations.AddField(
            model_name='pingresult',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
