# Generated by Django 4.0 on 2023-10-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorWeb', '0018_delete_ping_pingresult_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pingresult',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
