# Generated by Django 4.0 on 2023-10-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitorWeb', '0019_alter_pingresult_is_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('cno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('content', models.TextField()),
            ],
        ),
    ]
